### ISSUE TITLE
Allow user to deselect geometry

### ISSUE THREAD

**Issue by danrademacher** [clhenrick/nyc-crash-mapper#59]
Currently it is not easy to deselect a geometry once a user selects it.

Add an X next to the geom label to allow it to be dismissed:

e.g. `NYPD Precinct        101 X` ?

**Comment by clhenrick** [comment]
Logic

- action that causes geo identifier to become null / undefined

- map redisplays polygons for same geography type

- map zooms back out to all of NYC

UI:

- filter by area text read out needs a way of deselecting ("X")

- triggering the deselect action removes identifier text but keeps geo button active
